# Copyright 2025 InfluxData
# Author: Suyash Joshi (sjoshi@influxdata.com)

[agent]
  interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  flush_interval = "${TELEGRAF_COLLECTION_INTERVAL}"
  hostname = "${HOSTNAME}"

[[inputs.cpu]]
  percpu = true
  totalcpu = true
  collect_cpu_time = false
  report_active = true

[[inputs.mem]]

[[inputs.disk]]
  mount_points = ["/"]
  ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.diskio]]
  devices = ["sda", "sdb", "nvme0n1"]
  skip_serial_number = true

[[inputs.net]]
  interfaces = ["eth*", "en*"]
  ignore_protocol_stats = false

[[inputs.system]]

# --- IBM i DATA ADAPTER ---
[[inputs.http]]
  ## Use the service name "node-api" to connect to the API running in the "node-api" container
  urls = ["http://node-api:3005/api/status"]
  method = "GET"
  timeout = "5s"
  data_format = "json"
  name_override = "ibm_i_stats"

[[outputs.influxdb_v2]]
  urls = ["http://${INFLUXDB_HOST}:8181"]
  token = "${INFLUXDB_TOKEN}"
  organization = "${INFLUXDB_ORG}"
  bucket = "${INFLUXDB_BUCKET}"
